### ISSUE TITLE
版本号及版本更新错误（未对应操作系统）

### ISSUE THREAD

**Issue by yuyandong** [Xmader/hydrogen#1]
再次表示对 Xmader 的感谢！

在这里提两个小瑕疵，以便后续更新：

![image](https://user-images.githubusercontent.com/11476857/42482842-82cfca08-841c-11e8-9f10-97fb0a1b3b4c.png)
在关于那里是 1.1.10，实际我使用的是xmader 更新的 1.2.1

不过根据提示点升级后，自动更新下载的是linux 版
![image](https://user-images.githubusercontent.com/11476857/42482870-b1f9c4b4-841c-11e8-98ef-76340d4f5afe.png)

**Comment by Xmader** [comment]
感谢 yuyandong，
现在的v1.2.3版已修复这两个bug
