### ISSUE TITLE
文本编辑框滚动条-文档输入末尾增加行，滚动条不自动滚动

### ISSUE THREAD

**Issue by yuyandong** [Xmader/hydrogen#2]
原Mac 1.1.10 版本就存在的问题，Xmader 你看看有没有可能更新修正？谢谢

我不清楚术语上如何描述，按我的理解来说就是：

- 其他文本编辑软件，在最末一行书写时，按下enter 增加所需「行」后，比如增加 3 行，滚动条会自动滚动显现所增加「行」，但是Hydrogen 没有自动跳到并显示所需文本空间。

![image](https://user-images.githubusercontent.com/11476857/42483072-fc13f96a-841d-11e8-9eee-e317b4a616b6.png)

**Comment by Xmader** [comment]
感谢 yuyandong，
现在的v1.2.6版已解决这个问题
