### ISSUE TITLE
每次重新启动都出现 Tips 界面

### ISSUE THREAD

**Issue by yuyandong** [Xmader/hydrogen#3]
目前在Mac 系统里面用1.2.8 版本，之前不经常退出，今日无意退出后发现，每次打开Hydrogen，它都会自己弹出初始界面的那个使用说明界面。

建议修复，默认安装一次后，就不在重启后开启了。

另外，Control +s 在 Mac 版，快捷键是否可以调整为 Command+s ？（不改也无妨）

感谢 Xmader 快速有效的更新！

**Comment by Xmader** [comment]
感谢yuyandong,
这个问题在最新的v1.2.9版中已解决

**Comment by yuyandong** [comment]
厉害，高效！！感谢！！

**Comment by yuyandong** [comment]
不过1.29 Mac 版本还是会出现 使用说明界面。 好事是，它自己启动后自己会消失。有劳再测试下

**Comment by yuyandong** [comment]
我错了，我后面反复测试后，发现已经没有tips 界面了。抱歉！
