### ISSUE TITLE
删除任务失败 

### ISSUE THREAD

**Issue by eric6666662** [Xmader/hydrogen#5]
![gif](http://thyrsi.com/t6/625/1544089528x2890186050.gif)

**Comment by eric6666662** [comment]
系统：manjaro18-xfce4 
软件版本：1.2.9

**Comment by Xmader** [comment]
您好，
hydrogen中的根任务是不能被删除的，
这个只在hydrogen的帮助中有提及，我将在下一个版本中添加更友好的提示。
![screenshot](https://user-images.githubusercontent.com/16057139/49581586-5bc2d400-f98d-11e8-87f8-f5a772bcbbf4.png)

**Comment by eric6666662** [comment]
谢谢
